"""empty message

Revision ID: 06b3aa1da507
Revises: 3df026e75c61
Create Date: 2022-01-22 12:19:49.109380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b3aa1da507'
down_revision = '3df026e75c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('CurrentpatientID', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('fullName', sa.String(length=100), nullable=True),
    sa.Column('regtype', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=100), nullable=True),
    sa.Column('billto', sa.String(length=100), nullable=True),
    sa.Column('testspriority', sa.String(length=100), nullable=True),
    sa.Column('testscheduletype', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.String(length=100), nullable=True),
    sa.Column('discount', sa.String(length=100), nullable=True),
    sa.Column('equalltax', sa.String(length=100), nullable=True),
    sa.Column('total', sa.String(length=100), nullable=True),
    sa.Column('paymentmethod', sa.String(length=100), nullable=True),
    sa.Column('payment', sa.String(length=100), nullable=True),
    sa.Column('referenceOrchange', sa.String(length=200), nullable=True),
    sa.Column('sessionconfirm', sa.String(length=100), nullable=True),
    sa.Column('paymentconfirm', sa.String(length=100), nullable=True),
    sa.Column('cashier', sa.String(length=100), nullable=True),
    sa.Column('invoicemnemonics', sa.String(length=2100), nullable=True),
    sa.Column('invoicetestname', sa.String(length=2100), nullable=True),
    sa.Column('invoiceprice', sa.String(length=2100), nullable=True),
    sa.Column('invoicetat', sa.String(length=2900), nullable=True),
    sa.Column('transactTime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('phlebotomy_processed', sa.Boolean(), nullable=True),
    sa.Column('paymentupdateamount', sa.String(length=100), nullable=True),
    sa.Column('paymentupdateby', sa.String(length=100), nullable=True),
    sa.Column('paymentupdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('barcode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
