"""empty message

Revision ID: 3df026e75c61
Revises: 43dc8ac27621
Create Date: 2022-01-22 12:14:59.383100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df026e75c61'
down_revision = '43dc8ac27621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patientFirstname', sa.String(length=100), nullable=True),
    sa.Column('patientLastname', sa.String(length=100), nullable=True),
    sa.Column('patientMiddlename', sa.String(length=100), nullable=True),
    sa.Column('patientSex', sa.String(length=100), nullable=True),
    sa.Column('patientTitle', sa.String(length=100), nullable=True),
    sa.Column('ageGrade', sa.String(length=100), nullable=True),
    sa.Column('patientDateofBirth', sa.String(length=100), nullable=True),
    sa.Column('patientStatus', sa.String(length=100), nullable=True),
    sa.Column('patientType', sa.String(length=100), nullable=True),
    sa.Column('patientID', sa.String(length=100), nullable=True),
    sa.Column('patientEmail', sa.String(length=100), nullable=True),
    sa.Column('patientAltEmail', sa.String(length=100), nullable=True),
    sa.Column('patientPhonenumber', sa.String(length=100), nullable=True),
    sa.Column('patientAltPhonenumber', sa.String(length=100), nullable=True),
    sa.Column('patientwhatsappnumber', sa.String(length=100), nullable=True),
    sa.Column('patientAddress', sa.String(length=100), nullable=True),
    sa.Column('patientCity', sa.String(length=100), nullable=True),
    sa.Column('patientState', sa.String(length=100), nullable=True),
    sa.Column('patientCountry', sa.String(length=100), nullable=True),
    sa.Column('patientpersonalEnroledby', sa.String(length=100), nullable=True),
    sa.Column('patientCompanyname', sa.String(length=100), nullable=True),
    sa.Column('patientCorporateContactperson', sa.String(length=100), nullable=True),
    sa.Column('patientCorporateEmail', sa.String(length=100), nullable=True),
    sa.Column('patientAltCorporateEmail', sa.String(length=100), nullable=True),
    sa.Column('patientCorporatePhone', sa.String(length=100), nullable=True),
    sa.Column('patientCorporateAltPhone', sa.String(length=100), nullable=True),
    sa.Column('patientCorporatewhatsappnumber', sa.String(length=100), nullable=True),
    sa.Column('patientCorporateAddress', sa.String(length=100), nullable=True),
    sa.Column('patientCorporateCity', sa.String(length=100), nullable=True),
    sa.Column('patientCorporateState', sa.String(length=100), nullable=True),
    sa.Column('patientCorporateCountry', sa.String(length=100), nullable=True),
    sa.Column('patientCorporateEnroledby', sa.String(length=100), nullable=True),
    sa.Column('enrolment_Time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('patientID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
