"""empty message

Revision ID: 43dc8ac27621
Revises: 
Create Date: 2022-01-22 12:06:43.015151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43dc8ac27621'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labtests',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('testType', sa.String(length=100), nullable=True),
    sa.Column('testBottleType', sa.String(length=100), nullable=True),
    sa.Column('testName', sa.String(length=200), nullable=True),
    sa.Column('testmnemonics', sa.String(length=100), nullable=True),
    sa.Column('testDetails', sa.String(length=2000), nullable=True),
    sa.Column('testTAT', sa.String(length=100), nullable=True),
    sa.Column('testPrice', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('labtests')
    # ### end Alembic commands ###
